# Generated by Django 5.1.4 on 2024-12-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jovial", "0003_about_category_home_portfolio_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
