# Generated by Django 5.1.4 on 2024-12-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jovial", "0004_rename_skills_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home",
            old_name="geetings",
            new_name="greeting",
        ),
    ]
