# Generated by Django 5.1.4 on 2024-12-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jovial", "0005_rename_geetings_home_greeting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="picture",
        ),
        migrations.AlterField(
            model_name="home",
            name="greeting",
            field=models.CharField(max_length=15),
        ),
    ]
